#security config
cors.allowed-origins=http://192.168.2.242:4200

#etat config
etat.inactif.code=0
etat.actif.code=1
etat.proforma.code=2
etat.reelle.code=3
etat.paye.code=4

#type_mouvement config
type.mouvement.renseignement.id=TPM-00000001
type.mouvement.reservation.id=TPM-00000002
type.mouvement.occupation.id=TPM-00000003
type.mouvement.classement.id=TPM-00000004

#type_client config
type.client.personne.id=TPC-00000001
type.client.entreprise.id=TPC-00000002

#remise config
delai.paiement.jour=3
preparation.signalement.jour=2
avance.paiement=50
frequence.default.id=FRQ-00000001
facture.remise=0
heure.paiement.delai=72

frequence.jour.id=FRQ-00000001
frequence.nuit.id=FRQ-00000002
frequence.heure.id=FRQ-00000003
frequence.mois.id=FRQ-00000004

type.notification.danger.id=TPNF-00000001
type.notification.signalement.id=TPNF-00000002

schedule.hour=0 1 0 * * *

facture.proforma.export.path=/reports/proforma.jrxml
facture.reelle.export.path=/reports/facture.jrxml
contrat.export.path=/reports/contrat.jrxml
my.mail=ccl.cnaps@gmail.com
