spring.application.name=gestion-ccl

#configuration oracle server
#spring.datasource.url=jdbc:oracle:thin:@192.168.1.100:1521:M20

#configuration oracle locale
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/ORCLPDB1

spring.datasource.username=DEV_DEPL
spring.datasource.password=DEV04
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect
spring.jpa.properties.hibernate.jdbc.time_zone=GMT

#hikariCP
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.max-lifetime=570000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.validation-timeout=3000
spring.datasource.hikari.keepalive-time=300000
spring.datasource.hikari.auto-commit=true
logging.level.com.zaxxer.hikari=DEBUG

#security-config
spring.config.import=classpath:gestion.ccl.properties

#mail-configuration
spring.mail.host=192.168.1.104
spring.mail.port=25
spring.mail.username=no-reply@cnaps.mg
spring.mail.password=35R3VjJ76rJRSxGjueZP94c65drt2N
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
#Timeout
spring.mail.properties.mail.smtp.connectiontimeout=8000
spring.mail.properties.mail.smtp.timeout=8000
spring.mail.properties.mail.smtp.writetimeout=8000
