#security config
cors.allowed-origins=http://localhost:4200

#etat config
etat.inactif.code=0
etat.actif.code=1
etat.proformat.code=2
etat.reelle.code=3


#type_mouvement config
type.mouvement.renseignement.id=TPM-00000001
type.mouvement.reservation.id=TPM-00000002
type.mouvement.occupation.id=TPM-00000003
type.mouvement.classement.id=TPM-00000004

#type_client config
type.client.personne.id=TPC-00000001
type.client.entreprise.id=TPC-00000002

#remise config
facture.remise=50
